[package]
name = "ukendio/robloxmath"
version = "0.0.1-a.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
TestEZ = "roblox/testez@0.4.1"
Llama = "shanebutt/llama@1.1.0"
